/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e8e8e8",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#5d6260",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#a1d2b1",
        "on-primary-container": "#77a688",
        "on-surface": "#1a1c1c",
        "inverse-on-surface": "#f0f1f1",
        "on-error-container": "#93000a",
        "primary-container": "#0b3b24",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#224f36",
        "primary-fixed-dim": "#a1d2b1",
        "background": "#f9f9f9",
        "outline": "#717972",
        "outline-variant": "#c1c9c0",
        "on-primary-fixed": "#002111",
        "on-tertiary-container": "#84a297",
        "surface-container": "#eeeeee",
        "surface-variant": "#e2e2e2",
        "surface-container-highest": "#e2e2e2",
        "on-tertiary-fixed-variant": "#314c43",
        "on-secondary-fixed": "#181c1c",
        "tertiary-container": "#1d3830",
        "secondary-container": "#dadedc",
        "surface-container-low": "#f3f3f4",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed-variant": "#434847",
        "tertiary-fixed-dim": "#afcdc2",
        "secondary-fixed": "#dfe3e1",
        "inverse-surface": "#2f3131",
        "primary-fixed": "#bdeecc",
        "tertiary-fixed": "#cae9dd",
        "on-tertiary-fixed": "#042019",
        "secondary-fixed-dim": "#c3c7c6",
        "secondary": "#5b5f5e",
        "error-container": "#ffdad6",
        "on-background": "#1a1c1c",
        "primary": "#002413",
        "tertiary": "#06231b",
        "surface-dim": "#dadada",
        "on-surface-variant": "#414943",
        "surface": "#f9f9f9",
        "surface-tint": "#3b674d",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
